### PR TITLE
omeka/omeka-s#907: adding error message if no post data received

### PR DESCRIPTION
**Pull request by crism**
Not wedded to this wording, but it does the job.

### CODE REVIEW

**Comment by zerocrates** [comment]
I think I'd like to try to solve this in a way that it's solved across the whole UI, rather than having to deal with it piecemeal anywhere where there's a POST. (Even though file uploads are the most common cause, they're not the only one).

**Comment by crism** [comment]
I’m not sure there’s another place to put it; this pattern could easily be applied elsewhere. It’s only relevant where there’s already a check for `isPost()`, and seems a lot easier than asking the `Form` to try and figure out if its fields are all empty after they’ve been set. Although, hm, the check could be in `setData()`.

**Comment by crism** [comment]
Ah… a bigger problem is that any really global changes would be in `Form` itself, which is part of ZendFramework, and so a much more radical change than anything restricted to Omeka S. The change could go in `ResourceForm` in this case, but it would need to be similarly implemented in each appropriate subclass of `Form`…

**Comment by crism** [comment]
@zerocrates: This seems to handle the problem. As before, not wedded to the exact wording, but this seems a heck of a lot clearer to confused users.

**Comment by crism** [comment]
As per #907 discussion, this is probably not the right approach and has unpleasant side-effects.

**Pull request closed without merging**
