### PR TITLE
Version notification

### LINKED ISSUE #1144: New version notification
A la Classic.

We could probably either hook it to Github's "latest release" API, or use the same system Classic uses where we host an exceedingly simple API just declaring the latest released version.

### PR DESCRIPTION
**Pull request by jimsafley**
fixes #1144 #1146

### CODE REVIEW

**Comment by zerocrates** [comment]
Should use HTTPS for the addons JSONs as well.

**Comment by zerocrates** [comment]
We probably should lose the "Click here" in all those messages as we don't really use that pattern elsewhere. The main S check should probably just say "get the new version" too, since it's really pointing at the download page and not "instructions" per se.

**Comment by jimsafley** [comment]
I suppose the notifications need styling? @kimisgold

**Comment by zerocrates** [comment]
Yes, I was thinking so.

**Pull request merged**
