### PR TITLE
Fixed display of tabs on resource edit page when tabs are numerous.

### PR DESCRIPTION
**Pull request by Daniel-KM**

### CODE REVIEW

**Comment by kimisgold** [comment]
From what I can tell, the tabs are already wrapping in this view. Adding flexbox creates and odd overlap with the main form. 

image

Entirely possible I'm missing something. Could you share screenshots of the problem you're trying to solve alongside how your solution addresses it?

**Comment by Daniel-KM** [comment]
It works for me. In fact, the issue is not on edit page, but on show page.
Capture d’écran du 2023-02-27 10-53-08

**Comment by kimisgold** [comment]
I think setting `clear: both` on `.active.section` might get the same result without causing more issues on the edit view.

**Comment by Daniel-KM** [comment]
OK.

**Pull request merged**
