### PR TITLE
Fix some alerts from LGTM

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
See https://lgtm.com/projects/g/omeka/omeka-s/ for these and some more alerts.

**Comment by zerocrates** [comment]
We generally use var and not let elsewhere so for consistency those missing declarations should probably be "var"s.

**Comment by stweil** [comment]
I updated the pull request to use `var` instead of `let`.

**Comment by zerocrates** [comment]
After asking for that change I thought again, noting we have a bit of a hodgepodge of approaches on let/const/var already so this probably didn't really hurt any, but thanks for changing it.

**Pull request merged**
