### PR TITLE
Fixed check of slugs.

### PR DESCRIPTION
**Pull request by Daniel-KM**
The check of slugs is not the same in adapters and in routes.config.ini lines https://github.com/omeka/omeka-s/blob/develop/application/config/routes.config.php#L21 and next ones.

### CODE REVIEW

**Comment by zerocrates** [comment]
Can you add "underscores, " to the error texts also, so it accurately states the allowed set?

**Comment by zerocrates** [comment]
Thanks!

**Comment by Daniel-KM** [comment]
Done.

**Comment by zerocrates** [comment]
For some Github thinks your changes are from 19 hours ago so they're sorting oddly on here... maybe a clock or timezone problem on your system? Not a problem, just interesting.

**Pull request merged**
