### PR TITLE
Add filewriter trait to allow filesystem mocks

### PR DESCRIPTION
**Pull request by stl74**
Allow to mock filesystem easily (needed for  the migration of Archive Repertory module)

### CODE REVIEW

**Comment by zerocrates** [comment]
It's not really clear to me what this is for if its not being used anywhere.

**Comment by stl74** [comment]
Hi,
I need this for integration tests,.
Example here : https://github.com/biblibre/omeka-s-module-ArchiveRepertory/blob/master/test/Controller/ArchiveRepertoryControllerTest.php (WIP)
If you have another solution to not write on filesystem i'd be pleased to implement it.

**Comment by zerocrates** [comment]
I think it would be simpler to provide an alternate File Store instance entirely that writes to in-memory storage rather than adding a switchable "writer" within the LocalStore. Then whatever features needed for introspection or whatever for testing within the memory-based store can just be confined to that object alone, rather than necessitating modifications to the LocalStore as done here.

**Comment by stl74** [comment]
Ok . I move the localstore mock into biblibre/omeka-s-test-helper

**Pull request closed without merging**
