### PR TITLE
Global settings event

### PR DESCRIPTION
**Pull request by patrickmj**
Moves around the events for adding to global settings page, dividing it into two (one for elements, one for input filters), and making those calls from the forms, not the controller. That means that any modules currently using the one from the controller will need to switch.

Scope moved beyond the advertised global settings page to also include same pattern in site settings.

### CODE REVIEW

**Comment by patrickmj** [comment]
Something's still wrong in SiteSettings

**Comment by patrickmj** [comment]
I think all the confusion between modules and filters is sorted out now

**Comment by zerocrates** [comment]
Can we undo all those extra `ViewModel` and whitespace changes in the site controller? Only the Event `use` line change should have been required.

**Comment by patrickmj** [comment]
I suppose. It's just the result of running the fixer on the code. Is that to be avoided?

**Comment by zerocrates** [comment]
I suppose it depends how you're running the fixer. If you're using the rules that are checked into the repository and are used for the tests, then it should be fine. I suspect this is the result of using some other ruleset, probably the defaults.

**Pull request merged**
