### PR TITLE
Ckconfig

### PR DESCRIPTION
**Pull request by patrickmj**
Any thoughts on
1 how the configuration is pulled in
2. what those toolbars should look like. In the config file, it's pretty easy to move things around as needed/desired

### CODE REVIEW

**Comment by zerocrates** [comment]
What do you mean exactly by the first point? Are there specific alternatives you have in mind?

**Comment by patrickmj** [comment]
I don't have any specific alternatives in mind. That was more a call for whether others know of better approaches.

**Comment by zerocrates** [comment]
I just meant, what does the question mean? "how it's pulled in" meaning the config file vs. direct configuration, or something else?

**Comment by patrickmj** [comment]
Just whether what I'm doing in https://github.com/omeka/omeka-s/blob/ckconfig/application/src/Media/Handler/HtmlHandler.php#L23 and https://github.com/omeka/omeka-s/blob/ckconfig/application/src/Media/Handler/HtmlHandler.php#L69 with the `$view->assetUrl()` business looks right.

**Comment by zerocrates** [comment]
It looks OK to me

**Comment by patrickmj** [comment]
:beers: :+1:

**Comment by zerocrates** [comment]
As for whether the toolbars are right, I seem to remember some discussion with @kimisgold about whether to alter the styles/markup for the Media so the editor could take up the full width. I'd think a yes/no on that point would affect what was acceptable/desired as far as toolbar buttons

**Comment by kimisgold** [comment]
It looks fine to me. The interface is more robust than any of the other ways of adding media, so it looks busier and clunkier comparatively. It might be a matter of finding a better skin, but I can address that later—looks good for merging now.

**Pull request merged**
