### PR TITLE
Fixed GD thumbnailing of an image with an icc profile.

### PR DESCRIPTION
**Pull request by Daniel-KM**
When an image has an icc profile and gd is used, colors are no kept. This pr fixes it. 
The issue may be the same for imagick, but it depends on the version. A fix for it can be done too, like in https://github.com/Daniel-KM/LibraryDeepzoom/pull/1.

### CODE REVIEW

**Comment by zerocrates** [comment]
So this just copies over the ICC profile from the input to the output; it's not doing any actual color conversion, correct?

**Comment by Daniel-KM** [comment]
yes, it's a simple copy of the profile. You may find another way to extract/copy the profile, but the library works well.

**Comment by Daniel-KM** [comment]
You can try with such an image : https://i.stack.imgur.com/p42W6.jpg

**Comment by Daniel-KM** [comment]
Maybe a conversion may be a better way, but often unperfect.

**Pull request merged**
