### PR TITLE
Allowed to search by id with api endpoint.

### PR DESCRIPTION
**Pull request by Daniel-KM**
In internal api, it is possible now to search with a list of ids. It is not possible by endpoint, so this fixes it.

### CODE REVIEW

**Comment by zerocrates** [comment]
I'm wondering if we might just want to turn off completely the ability for this to look up "the ID" from the query string, since that's really not the way our REST API is intended to work. So to instead override this to just look only at the RouteMatch for an ID.

**Comment by Daniel-KM** [comment]
It is very useful to request the api with a list of ids, so if `id=xxx` is useless, `id[]=xxx` should be kept. Is it that you mean?

**Comment by zerocrates** [comment]
I think we're on the same page with your revised commit here: I just meant to use the RouteMatch only in this method so that a user can query on either `?id=X` or `?id[]=X&id[]=Y` and we'll still correctly do a "search" instead of the current behavior where the Laminas layer is seeing an `id` key and interpreting the request as a "read."

**Comment by Daniel-KM** [comment]
Yes, so my second commit is good: only `/api/items/xxx` is a read, everything else is a search.

**Comment by zerocrates** [comment]
OK, great.

**Pull request merged**
