### PR TITLE
Feature/iiif api v3

### PR DESCRIPTION
**Pull request by Daniel-KM**
OpenSeadragon has only beta support of iiif api, but it is enough for now.

### CODE REVIEW

**Comment by Daniel-KM** [comment]
And another renderer is needed, because iiif v3 allows to display audio and video, not only images.

**Comment by zerocrates** [comment]
This looks good from the spec.

Do you happen to know of any live IIIF Image API 3.0 implementations in the wild?

**Comment by Daniel-KM** [comment]
I was looking, but in fact the module [Image Server](https://github.com/Daniel-KM/Omeka-S-module-ImageServer) I'm finishing is the only one I found.

**Comment by zerocrates** [comment]
OK. I figured they would be hard to come by at this time.

**Comment by regisrob** [comment]
Actually there are a few existing IIIF v3 implementations in the wild, both on the client and server side, and both for the Image and Presentation API. Some institutions also started to expose IIIF v3 contents (Stanford, Oxford, NCSU etc.). 

@zerocrates Is having real IIIF v3 URLs to test with what you were looking for? Or rather other software implementations?

**Comment by zerocrates** [comment]
Just URLs, for the immediate term.

**Pull request closed without merging**
