### PR TITLE
Added a link to show current resource in user page.

### PR DESCRIPTION
**Pull request by Daniel-KM**
To finish https://github.com/omeka/omeka-s/pull/1283 with a link to resource show, that is useful when some property are hidden in public side.

### CODE REVIEW

**Comment by Daniel-KM** [comment]
Rebased.

**Comment by zerocrates** [comment]
All this is doing is always presenting the View (or Show) link, regardless of whether the user can edit the resource in question, correct?

**Comment by zerocrates** [comment]
I think we'd want to keep the English string as "View" here, even though it doesn't match up with the name of the action... it's consistent with other places like "View Public" on sites admin. Describes what the user is doing rather than what Omeka is doing.

**Comment by Daniel-KM** [comment]
For question 1, there is no check for "view", but rights are checked to display the edit action or not.

**Pull request merged**
