### PR TITLE
Fix some typos (most of them found by codespell)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
Ping?

**Comment by zerocrates** [comment]
Ah yes, sorry. I thought I'd responded to this before.

I think this mostly looks good... who knew we had so many typos in comments. One note: "invokable" is the Zend/Laminas terminology/language when we're using it in comments, so I don't think we'll be changing that to "invocable."

**Comment by stweil** [comment]
I removed the changes for "invocable" now from the pull request.

**Comment by stweil** [comment]
> who knew we had so many typos in comments

That's normal for projects which never used a spell checker like codespell before, so no reason to be worried. :-)

**Comment by zerocrates** [comment]
Thanks.

Oh and sorry, I forgot to mention... I don't know what the situation is with the RDF/XML/OWL files in the application/data/vocabularies folder... those are externally-sourced standardized files and we probably don't want to be fixing their typos unilaterally. Probably best to remove those also.

**Comment by stweil** [comment]
The string _"A foaf:LabelProperty is any RDF property with texual values that serve as "_ comes from `application/data/vocabularies`, but is translated in `application/language`, so I think it has to be reverted there, too.

**Comment by stweil** [comment]
> I think it has to be reverted there, too.

Done now.

**Comment by zerocrates** [comment]
Thanks for making those changes.

**Pull request merged**
