### PR TITLE
Slugify non-ascii characters.

### PR DESCRIPTION
**Pull request by Daniel-KM**
Slugify "café" to "cafe", not "caf-".

### CODE REVIEW

**Comment by zerocrates** [comment]
The only problem here is that this ends up mandating the intl extension, something we've tried to avoid as it's missing on lots of hosts (yes, even though it's bundled with PHP since forever).

We use it ourselves other places, but it tends to be in ways that we can just skip it if it's not there (as in the date processing code).

Doing this with a lookup table or maybe iconv with TRANSLIT are possible alternatives, either altogether or in the case that the Transliterator class can't be found. Simply skipping the transformation in that case could be fine too.

**Comment by Daniel-KM** [comment]
Just added a check for the extension and added an alternative with iconv. iconv doesn't convert "é" and some common characters, but it converts some others ones.

**Comment by zerocrates** [comment]
Just for extra safety, we should probably stick the `iconv` behind a check that the `iconv` extension is loaded as well.

**Comment by zerocrates** [comment]
Thanks.

**Pull request merged**
