### PR TITLE
Translate vocabulary, property, and class strings

### PR DESCRIPTION
**Pull request by jimsafley**
refs #336

### CODE REVIEW

**Comment by jimsafley** [comment]
One annoying thing `msgcat` does is add a comment containing the name of the temp file created for `extract-vocab-strings`, like so:
```
#. #-#-#-#-#  null1188807331.pot  #-#-#-#-#
#. Property label for Dublin Core:title
#: application/view-admin/omeka/admin/item-set/browse.phtml:6
...
msgid "Title"
msgstr ""
```
This happens only when a message is shared between `extract-vocab-string` and `xgettext` or `extract-tagged-strings`, otherwise it's like so:
```
#. Class label for Dublin Core:Location
msgid "Location"
msgstr ""
```
I see that Omeka classic got around this by combining `Omeka.base.pot` when running `xgettext` using the `--join-existing` flag. Looking at the resulting pot file, it seems the inclusion of the `--add-comments=/` flag prevents the above annoyance from occurring, like so (note the forward slash):
```
#. / Chicago-style item citation: two authors
#: application/models/Item.php:457
#, php-format
msgid "%1$s and %2$s"
msgstr ""
```

**Comment by zerocrates** [comment]
Does `--use-first` to msgcat avoid the extra comments?

**Comment by jimsafley** [comment]
Adding `--use-first` removes the shared `extract-vocab-strings` comments altogether (but not the non-shared ones).

**Comment by jimsafley** [comment]
Note that this is not a bug, just an annoyance.

**Pull request merged**
