### PR TITLE
Convert the user bar into a helper

### PR DESCRIPTION
**Pull request by Daniel-KM**
Based on the previous pull request, I converted the user bar into a helper, so it is possible to add new tools in it. In fact, there are two ways to add new tools: a helper, so it's possible to upgrade the https://github.com/omeka/plugin-EditLink, or a trigger, or even a block, but it's simpler via a helper and modules for now.

Note that this change requires an update to the official themes, since the user bar is now just `echo $this->userBar();` (the partial is still available, but it requires a value for "user" and checks are not done). I can push this update if needed.

### CODE REVIEW

**Comment by Daniel-KM** [comment]
The last commit avoids to update old themes, but the check for the user bar should be done when the helper is not used.

**Comment by zerocrates** [comment]
I like this change, but I think we're going to wait until post-1.0 for it.

**Comment by Daniel-KM** [comment]
Rebased.

**Comment by Daniel-KM** [comment]
Rebased.

**Comment by zerocrates** [comment]
I'm understanding the change correctly that the bar will render with no theme changes, but switching over to use the helper is required to get the always/never/logged-in switch to work, yes?

**Comment by Daniel-KM** [comment]
Last year, the idea was to avoid the upgrade of themes, so the upgrade works with any theme, and that's why the radio uses values "-1", "0", and "1", like a checkbox. These values can be changed if you want to require a change in themes.

**Pull request merged**
