### PR TITLE
Chosen layout fix

### PR DESCRIPTION
**Pull request by jimsafley**
See #1001

### CODE REVIEW

**Comment by zerocrates** [comment]
I pulled this in but on closer inspection it causes some problems:

- If the viewport is fairly short, it will try to "drop up" even selects at the top of the screen, causing them to clip off the top
- After the first "drop up", the menu sits in the markup below the select and takes up space (giving you extra scroll distance in the sidebar). If you scroll into that space, you get weird results because the menu moves when it goes to drop up, so your pointer is sitting over the list and will immediately select the entry under it if you mouseup.

**Comment by zerocrates** [comment]
@kimisgold the problem with the "reserves extra space" thing might be solvable within our CSS: we can add `overflow: hidden` to .chosen-container, and also `overflow: visible` to .chosen-container.chosen-with-drop

We can probably tweak the script to prevent "drop up" if there's not enough space above the element to fit the menu as well.

#1001 wasn't really Chosen-specific though, instead a problem with the styling of the sidebar and the button, so it's possible that reversion is a reasonable option as well.

**Comment by zerocrates** [comment]
@kimisgold @jimsafley We need to decide what to do here: either try to do some fixes for these problems, or just back out this change.

I _believe_ that the other work on #1001 means that backing this out won't cause a problem (but it will still cause the resource template sidebar to grow vertically when the Chosen select is opened).

**Comment by kimisgold** [comment]
I'm fine with the simplest solution of reverting, unless @jimsafley thinks the fixes to the dropup are comparably minimal to implement.

**Pull request merged**
