### PR TITLE
catch_connection_exceptions

### PR DESCRIPTION
**Pull request by elrossco22**
In the event MySQL goes away for any period of time, the full stack trace is outputted to all users including the MySQL credentials .. password etc.See screenshot below the password "Password123" is exposed.
[https://postimg.org/image/3zk2ymooh/](https://postimg.org/image/3zk2ymooh/)

### CODE REVIEW

**Comment by zerocrates** [comment]
Well that's definitely not for the best...

That fallback exception screen is pretty much a temporary placeholder. The standard "classic" answer to this problem is to not show any error details at all for any exception unless "development" mode is activated in the .htaccess.

Special handling for database exceptions is fine as well, though what does this PR result in for the user? It would seem like it'd cause a redirect to the installer, which would be a pretty confusing error experience.

**Comment by elrossco22** [comment]
Screenshot below of the result of this PR, All being perhaps a little confusing as it does say "Install"

https://postimg.org/image/td6xkhdj1/

We could create a custom page "site under maintenance" etc and have that displayed instead

**Comment by elrossco22** [comment]
@zerocrates Are there any thoughts in regards to my last comment, I'd be keen to wrap this up as its a security flaw ?

**Comment by zerocrates** [comment]
So to start what I've done is just restored the mode of operation from Classic: exception messages don't get printed to users at all unless the administrator has affirmatively set "development" mode on. So in the case of connectivity issues by default all that will now be seen is this:

error

**Comment by elrossco22** [comment]
@zerocrates Great, Thanks for the update. Whats the plan for this ? Is there a case for not using the Classic exception messages ?

**Comment by zerocrates** [comment]
Clarify for me: is the change I just mentioned of blanking the details by default, which I committed just before commenting, sufficient, or are you looking for something further?

**Comment by elrossco22** [comment]
@zerocrates Sorry just seen this, The blanking of details is fine for now.I'll close this

**Pull request closed without merging**
