### PR TITLE
Fix/translate plugin

### PR DESCRIPTION
**Pull request by Daniel-KM**
I removed these commits from the fix/ongoing one, because many files are modified, but it's just a replace. 

The use of $translate() is a little quicker to use than $this->translate(), but the main advantage is for the theme designers, because it is simpler to write.

### CODE REVIEW

**Comment by zerocrates** [comment]
OK. I knew I hadn't pulled those in so I was momentarily confused where they'd gone in your previous rebase.

**Comment by Daniel-KM** [comment]
And I didn't check if the strings that use the function `$translate()` can be extracted or not.

**Comment by Daniel-KM** [comment]
Rebased.

**Comment by Daniel-KM** [comment]
Rebased on 1.3.

**Pull request merged**
