### PR TITLE
Select media resources as values

### PR DESCRIPTION
**Pull request by jimsafley**
(refs #949)

### CODE REVIEW

**Comment by jimsafley** [comment]
@mebrett Testing: the `experimental-media-value` branch adds "Media" to the "Omeka resource" value type. You should _only_ see the "Media" button when editing an item. After selecting "Media", the sidebar should _only_ list media that's assigned to the item. After selecting the media resource, it should show up as normal on the edit form, alongside a media icon. After saving the item, the show page should render the media value as normal, alongside a media icon.

**Comment by mebrett** [comment]
Media option shows up with other Omeka S Resources when editing an item. Does not show up when adding an item as the media hasn't been ingested yet. 

When used, media show up displaying their title as link, with an icon (indicating media type?)
screen shot 2017-06-27 at 1 15 20 pm

**Comment by kimisgold** [comment]
@mebrett The icon indicates the value type, so the 'image' glyph is indicating it is a 'media' value (as opposed to 'item' or 'item-set' values).

**Comment by mebrett** [comment]
@kimisgold thanks for the clarification (I'm sure a user at some point will ask)

**Pull request merged**
